name: Build gitee

on:
  push:
    branches: [ master ]
  schedule:
    # Run every hour
    - cron: '0 * * * *'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v .

    

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Build website (automatic)
        file_pattern: docs/index.html
  
    - name: Clone source code 克隆源码
      run: |
        git clone https://github.com/wudongdefeng/rss.io.git wudongdefeng.github.io    
         
        git clone https://gitee.com/wudongdefeng/rss.git ~/gitee
        
    - name: copy some list files 复制文件
      run: |
        echo "https://wudongdefeng:${{ secrets.mima }}@gitee.com">~/.git-credentials
        cp ./docs/index.html ~/gitee/docs/index.html
    - name: Commit files 提交文件
      run: |
        cd ~/gitee
        git config --global credential.helper store
        git config --local user.email "${{ secrets.youxiang }}"
        git config --local user.name "wudongdefeng"
        git add .
        git commit -m "空投已送达" -a
        git push -u origin master   
